data:
  container_name: orocommerce_data
  image: djocker/orodata
source_code:
  container_name: orocommerce_source
  image: djocker/orocommerce
db:
  container_name: orocommerce_db
  image: mysql:5.5
  expose:
    - "3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=orocommerce
    - MYSQL_USER=orocommerce
    - MYSQL_PASSWORD=orocommerce
  volumes_from:
    - data
mail:
  container_name: orocommerce_mail
  image: catatnight/postfix
  expose:
    - "25"
  environment:
    - maildomain=localhost
    - smtp_user=user@localhost:password
minion:
  container_name: orocommerce_minion
  image: djocker/oromono
  links:
    - "db"
    - "mail"
  ports:
    - "3080:80"
    - "3088:8080"
  volumes_from:
    - data
    - source_code
  environment:
    - CMD_INIT_BEFORE=
    - CMD_INIT_CLEAN=
    - CMD_INIT_INSTALLED=
    - CMD_INIT_AFTER=
    - APP_DB_DRIVER=pdo_mysql
    - APP_DB_HOST=db
    - APP_DB_PORT=3306
    - APP_DB_USER=orocommerce
    - APP_DB_PASSWORD=orocommerce
    - APP_DB_NAME=orocommerce
    - APP_HOSTNAME=localhost
    - APP_MAILER_TRANSPORT=smtp
    - APP_MAILER_HOST=mail
    - APP_MAILER_PORT=25
    - APP_MAILER_ENCRYPTION=
    - APP_MAILER_USER=user
    - APP_MAILER_PASSWORD=password
    - APP_WEBSOCKET_BACKEND_PORT=8080  
    - APP_WEBSOCKET_FRONTEND_PORT=3088  
    - APP_SECRET=123456789  
    - APP_IS_INSTALLED=
